version: '3.8'  # Версия формата Docker Compose файла. Рекомендуется использовать последнюю стабильную версию.

name: "nuxt-fullstack"  # Имя проекта Docker Compose. Удобно для организации контейнеров.

services:  # Секция для описания сервисов, которые будут запускаться.
  postgres:  # Имя сервиса. Используется для обращения между контейнерами в одной сети.
    container_name: nuxt-postgres  # Имя контейнера. Упрощает поиск контейнера через `docker ps`.
    image: postgres:16-alpine3.19  # Образ PostgreSQL версии 16 на базе легковесного Alpine Linux.
    environment:  # Переменные окружения для настройки базы данных.
      POSTGRES_DB: 'nuxt-fullstack'  # Имя базы данных, которая будет создана при запуске.
      POSTGRES_USER: 'root'  # Имя пользователя для базы данных.
      POSTGRES_PASSWORD: 'root'  # Пароль для указанного пользователя.
      TZ: "UTC"  # Часовой пояс для корректной работы временных данных.
    ports:  # Проброс портов между хостом и контейнером.
      - '5432:5432'  # Локальный порт 5432 связан с портом 5432 контейнера (стандартный порт PostgreSQL).